version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ha2wqoq3jo2c"
s3_prefix = "todo"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
